"""
rag.py
------
This file contains:
  1. A placeholder Retrieval-Augmented Generation (RAG) pipeline that will
     eventually search embeddings of uploaded admission PDFs / brochures.
  2. `generate_ibm_response()` — the single integration point where IBM
     watsonx.ai (Granite model) will be plugged in later.
  3. A rule-based fallback response generator so the chatbot is fully
     functional today, using dummy JSON data, with zero external API calls.

--------------------------------------------------------------------------
HOW TO INTEGRATE IBM watsonx.ai LATER (Granite model)
--------------------------------------------------------------------------
1. `pip install ibm-watsonx-ai`
2. Set the following environment variables (e.g. in a .env file):
       WATSONX_API_KEY=<your api key>
       WATSONX_PROJECT_ID=<your project id>
       WATSONX_URL=https://us-south.ml.cloud.ibm.com
3. Inside `generate_ibm_response()` below, replace the placeholder logic
   with something like:

       from ibm_watsonx_ai.foundation_models import ModelInference
       from ibm_watsonx_ai import Credentials

       credentials = Credentials(
           url=os.getenv("WATSONX_URL"),
           api_key=os.getenv("WATSONX_API_KEY"),
       )
       model = ModelInference(
           model_id="ibm/granite-13b-chat-v2",
           credentials=credentials,
           project_id=os.getenv("WATSONX_PROJECT_ID"),
       )
       result = model.generate_text(prompt=prompt)
       return result

4. Keep the function signature identical (`generate_ibm_response(prompt, context)`)
   so routes.py never needs to change — only this file does.
--------------------------------------------------------------------------
"""

from utils import load_json_data, detect_intent


def retrieve_relevant_context(query: str):
    """
    PLACEHOLDER RAG RETRIEVAL FUNCTION.

    In a real implementation, this function would:
      1. Convert `query` into an embedding vector (e.g. using watsonx.ai
         embeddings or sentence-transformers).
      2. Perform a similarity search against a vector store (e.g. Chroma,
         FAISS, Milvus, or IBM watsonx.ai's vector index) containing
         chunks of uploaded admission PDFs / brochures.
      3. Return the top-k most relevant text chunks to be injected into
         the LLM prompt as context (this is the "R" in RAG).

    For now, it simply returns a static string describing what *would*
    normally happen, so the rest of the pipeline can be developed and
    tested end-to-end without a real vector database.

    Args:
        query: the student's question

    Returns:
        A string of "retrieved" context (dummy for now).
    """
    # TODO: Replace with real vector search once admission PDFs are indexed.
    return (
        "No indexed admission documents yet. Once PDFs are uploaded via "
        "/upload, this function will retrieve the most relevant passages "
        "from them to ground the AI's answer."
    )


def generate_ibm_response(prompt: str, context: str = ""):
    """
    PLACEHOLDER for IBM watsonx.ai (Granite) integration.

    This is the single function that must be updated when IBM watsonx.ai
    credentials are available. Everything else in the app (routes.py,
    the fallback generator below) is designed to keep working unchanged.

    Args:
        prompt: the user's question / instruction
        context: optional retrieved context (from retrieve_relevant_context)
                 to ground the model's answer (RAG pattern)

    Returns:
        A string response. Currently returns a clearly-labelled placeholder
        message so it's obvious in the UI that the real model isn't wired
        in yet.
    """
    # TODO: Replace this block with a real call to IBM watsonx.ai Granite.
    return (
        "[IBM Granite placeholder] This response will be generated by "
        "IBM watsonx.ai's Granite model once integrated. "
        f"Received prompt: '{prompt}'."
    )


def generate_fallback_response(message: str) -> str:
    """
    Rule-based chatbot logic that answers common admission questions using
    the dummy JSON data (courses, scholarships, fees) already in this repo.

    This keeps the /chat endpoint fully functional today. Once IBM Granite
    is integrated, this function can either be:
      - Removed entirely in favor of `generate_ibm_response`, or
      - Kept as an offline fallback if the IBM API is unreachable.

    Args:
        message: the raw user message from the chat UI

    Returns:
        A helpful, human-readable string response.
    """
    intent = detect_intent(message)

    if intent == "eligibility":
        return (
            "Eligibility criteria vary by course. For example, B.Tech programs "
            "require 10+2 with Physics, Chemistry and Mathematics (min. 60%), "
            "while MBA requires a bachelor's degree with a valid CAT/MAT/CMAT "
            "score. Ask me about a specific course for exact details!"
        )

    if intent == "courses":
        courses = load_json_data("courses.json")
        names = ", ".join(c["name"] for c in courses[:5])
        return f"We offer several programs including: {names}. Check the Course Finder page for full details."

    if intent == "hostel":
        return (
            "On-campus hostel accommodation is available for both boys and girls, "
            "with charges ranging from ₹85,000–₹1,10,000 per year depending on the "
            "course and room type. Mess facilities and Wi-Fi are included."
        )

    if intent == "placements":
        return (
            "Our placement cell works with 150+ recruiting partners. Average "
            "packages range from ₹4.5 LPA (BBA) to ₹9.2 LPA (MBA), with the "
            "highest package last year touching ₹32 LPA."
        )

    if intent == "fees":
        fees = load_json_data("fees.json")
        if fees:
            sample = fees[0]
            return (
                f"Fee structure varies by course. For example, {sample['course']} "
                f"costs approximately ₹{sample['totalPerYear']:,} per year "
                "(tuition + hostel + other charges). Visit the Fee Structure page for full details."
            )
        return "Please check the Fee Structure page for detailed course-wise fees."

    if intent == "scholarships":
        scholarships = load_json_data("scholarships.json")
        names = ", ".join(s["name"] for s in scholarships[:3])
        return f"We offer multiple scholarships including: {names}. Visit the Scholarship page for eligibility and deadlines."

    if intent == "documents":
        return (
            "Required documents typically include: 10th & 12th mark sheets, "
            "transfer certificate, migration certificate, category/income "
            "certificate (if applicable), passport-size photographs, and a "
            "valid ID proof. You can upload your admission documents on the "
            "Upload page for verification."
        )

    if intent == "admission_process":
        return (
            "The admission process is simple: 1) Fill out the online application, "
            "2) Upload required documents, 3) Pay the application fee, "
            "4) Attend counseling/entrance exam (if applicable), "
            "5) Receive your admission offer, 6) Confirm your seat by paying "
            "the admission fee."
        )

    if intent == "important_dates":
        return (
            "Applications for the upcoming academic year open August 1st and "
            "close September 15th, 2026. Counseling sessions begin late "
            "September. Exact dates may vary by course — check the FAQ page "
            "for the latest schedule."
        )

    # Default / general fallback
    return (
        "I can help you with eligibility, courses, hostel life, placements, "
        "fee structure, scholarships, required documents, the admission "
        "process, or important dates. Could you tell me a bit more about "
        "what you'd like to know?"
    )
