// FAQ.jsx
// Reusable FAQ accordion. Used both as a landing-page teaser section
// (id="faq" for Navbar linking) and inside the full FAQPage.
// Accepts an optional `items` override and a `compact` flag to only show
// the first few questions on the landing page.

import { useState } from "react";
import { ChevronDown } from "lucide-react";

export const DEFAULT_FAQS = [
  {
    q: "What documents are required for admission?",
    a: "You'll typically need your 10th & 12th mark sheets, transfer certificate, migration certificate, category/income certificate (if applicable), passport-size photographs and a valid ID proof. You can upload these on our Upload page.",
  },
  {
    q: "How do I check my eligibility for a course?",
    a: "Each course has specific eligibility criteria based on your qualifying exam and marks. Visit the Course Finder page or ask the Admission Chat directly, e.g. 'Am I eligible for B.Tech CSE with 72%?'",
  },
  {
    q: "Are scholarships available for all courses?",
    a: "Most scholarships apply across courses, though some (like sports quota) may have specific program restrictions. Check the Scholarship page for full eligibility details and deadlines.",
  },
  {
    q: "Is hostel accommodation guaranteed?",
    a: "Hostel seats are allocated on a first-come, first-served basis and are generally guaranteed for outstation students who apply within the first counseling round.",
  },
  {
    q: "Can I pay fees in installments?",
    a: "Yes, most courses allow semester-wise fee payment. Some scholarships also apply directly to your first installment. See the Fee Structure page for details.",
  },
  {
    q: "When will IBM watsonx.ai be integrated?",
    a: "The chat interface is already architected for it — see generate_ibm_response() in the backend's rag.py. Once IBM watsonx.ai credentials are added, responses will be generated by the Granite model instead of the current rule-based engine.",
  },
];

export default function FAQ({ items = DEFAULT_FAQS, compact = false }) {
  const [openIndex, setOpenIndex] = useState(0);
  const visibleItems = compact ? items.slice(0, 4) : items;

  return (
    <section id="faq" className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-24 scroll-mt-20">
      {!compact && (
        <div className="text-center mb-12">
          <span className="text-xs font-semibold tracking-wide text-brand-600 dark:text-brand-400 uppercase">
            Frequently asked
          </span>
          <h2 className="mt-3 text-3xl sm:text-4xl font-display font-bold text-slate-900 dark:text-white">
            Questions students ask us the most
          </h2>
        </div>
      )}

      <div className="space-y-3">
        {visibleItems.map((item, index) => {
          const isOpen = openIndex === index;
          return (
            <div
              key={item.q}
              className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(isOpen ? -1 : index)}
                className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left"
              >
                <span className="font-medium text-slate-800 dark:text-slate-100">{item.q}</span>
                <ChevronDown
                  size={18}
                  className={`shrink-0 text-brand-600 transition-transform ${isOpen ? "rotate-180" : ""}`}
                />
              </button>
              {isOpen && (
                <div className="px-5 pb-4 text-sm text-slate-600 dark:text-slate-400 leading-relaxed animate-fade-in">
                  {item.a}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}
